brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_indent = "Visual"
indent_style = "Visual"
generics = "Visual"
match_arm_blocks = false
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "One"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
